

# This file was *autogenerated* from the file LatticeMatrix.sage
from sage.all_cmdline import *   # import sage library

_sage_const_23 = Integer(23); _sage_const_3 = Integer(3); _sage_const_31 = Integer(31); _sage_const_15 = Integer(15); _sage_const_22 = Integer(22); _sage_const_21 = Integer(21); _sage_const_12 = Integer(12); _sage_const_20 = Integer(20); _sage_const_14 = Integer(14); _sage_const_19 = Integer(19); _sage_const_4 = Integer(4); _sage_const_18 = Integer(18); _sage_const_11 = Integer(11); _sage_const_17 = Integer(17); _sage_const_9 = Integer(9); _sage_const_16 = Integer(16); _sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_13 = Integer(13); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
N = _sage_const_23 
p = _sage_const_3 
q = _sage_const_31 

R = ZZ['x']
x = R.gen()

# Public key h
h_poly = R(-_sage_const_15 *x**_sage_const_22  - _sage_const_15 *x**_sage_const_21  - _sage_const_12 *x**_sage_const_20  - _sage_const_14 *x**_sage_const_19  + _sage_const_4 *x**_sage_const_18  + _sage_const_11 *x**_sage_const_17 
           - _sage_const_9 *x**_sage_const_16  + _sage_const_12 *x**_sage_const_15  - _sage_const_11 *x**_sage_const_14  + _sage_const_2 *x**_sage_const_12  + _sage_const_10 *x**_sage_const_11  + _sage_const_13 *x**_sage_const_10 
           - _sage_const_3 *x**_sage_const_9  + _sage_const_7 *x**_sage_const_8  - _sage_const_5 *x**_sage_const_6  + _sage_const_5 *x**_sage_const_5  + _sage_const_7 *x**_sage_const_4  - _sage_const_4 *x**_sage_const_3  + _sage_const_12 *x**_sage_const_2 
           - _sage_const_3 *x - _sage_const_12 )

h_coeffs = h_poly.list()
h_coeffs += [_sage_const_0 ] * (N - len(h_coeffs))

def build_ntru_lattice(h_coeffs, N, q):
    rows = []
    for i in range(N):
        row = [_sage_const_0 ] * (_sage_const_2  * N)
        row[i] = _sage_const_1 
        for j in range(N):
            row[N + j] = int(h_coeffs[(j - i) % N]) % q
        rows.append(row)
    for i in range(N):
        row = [_sage_const_0 ] * (_sage_const_2  * N)
        row[N + i] = q
        rows.append(row)
    return Matrix(ZZ, rows)

M = build_ntru_lattice(h_coeffs, N, q)

with open("example02-Lattice.txt", "w") as f:
    f.write("NTRU Lattice Matrix (46x46)\n")
    f.write(f"N = {N}, p = {p}, q = {q}\n\n")
    for row in M.rows():
        f.write("[" + ", ".join(str(c) for c in row) + "]\n")

print("Written to example02-Lattice.txt")


# Read the lattice matrix from file
rows = []
with open("example02-Lattice.txt", "r") as f:
    for line in f:
        line = line.strip()
        # Only process lines that start with '['
        if line.startswith("["):
            # Strip brackets and split by comma
            entries = line.strip("[]").split(",")
            row = [int(e.strip()) for e in entries]
            rows.append(row)

# Reconstruct the matrix and run LLL
M = Matrix(ZZ, rows)
L = M.LLL()

# Write LLL-reduced matrix to file
with open("example02-LLLMatrix.txt", "w") as f:
    f.write("NTRU LLL-Reduced Matrix (46x46)\n")
    f.write(f"N = {N}, p = {p}, q = {q}\n\n")
    for row in L.rows():
        f.write("[" + ", ".join(str(c) for c in row) + "]\n")

print("LLL-reduced matrix written to example02-LLLMatrix.txt")

